//importar las img

const projectsEn = [
    {id: 1,
    clase: "portfolioReact",
    link: "https://nicobonder.github.io/webdevportfolio/",
    title: "Click to open this project",
    name: "Portfolio",
    description: "My personal portfolio as Web Developer where you have all the ways to contact me and hire me. Yes, I know you are thinking about it. I used React.js, CSS and some HTML. I also used the Particles.js Library.",
    img: "",
    },
    {id: 2,
    clase: "content",
    link: "https://nicobonder.github.io/contentwriter/",
    title: "Click to open this project",
    name: "Content Writer",
    description: "I work as a content writer, so I made a web where I can show my services and my expertise. I created it using HTML, CSS and JavaScript. I also used the Animate On Scroll Library and the Typed.js Library.",
    img: "",
    },
    {id: 3,
    clase: "gout",
    link: "https://gout.vercel.app/",
    title: "Click to open this project",
    name: "goût",
    description: "Group project in which we created a social network dedicated to gastronomy. We used React.js, Material UI and Redux Toolkit in the Front End and Node Js, MySQL and Cloudinary in the Back End.",
    img: "",
    },
    /*{id: 4,
    clase: "tienda",
    link: "https://tiendaviajera.netlify.app/",
    title: "Click to open this project",
    name: "Coming soon!",
    description: "ecommerce to sell travelers ebooks. It was created with React.js and Material UI. It is Under Construction, but will be ready soon!",
    img: "",
    },*/
    {id: 5,
    clase: "apiCountries",
    link: "https://nicobondercountries.netlify.app/",
    title: "Click to open this project",
    name: "Countries API",
    description: "Api that returns the countries of the world. It was created with Vanilla JS and the Api from restcountries.",
    img: "",
    }
]

export default projectsEn;